version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: postgres:9.6
        environment:
          POSTGRES_USER: samply
          POSTGRES_PASSWORD: samply
          POSTGRES_DB: samply.searchbroker

    working_directory: ~/repo

    steps:
      - checkout

      - run: mvn -B package -Psamply

      - setup_remote_docker
      - run: docker build -t martinbreu/samply-searchbroker:${CIRCLE_SHA1} .
      - run: docker login -u martinbreu -p "${DOCKER_HUB_PASSWD}"
      - run: docker push martinbreu/samply-searchbroker:${CIRCLE_SHA1}
